### ISSUE TITLE
Hearth & Home Compatibility

### ISSUE THREAD

**Issue by atticoos** [projjm/Valheim-Player-Trading#1]
Upon selecting an item in the inventory, Player Trading crashes upon creating the following move-item effect with a `MissingMethodException`

https://github.com/projjm/Valheim-Player-Trading/blob/719172e500a3343f3154668e75a7f10ca5acd395/PlayerTrading/Patches/InventoryGuiPatches.cs#L186

Crash log:
![image](https://user-images.githubusercontent.com/656630/133829212-7acba737-e989-4738-a2d1-3d2e943698e8.png)

`EffectList.Create` has a new method signature
![image](https://user-images.githubusercontent.com/656630/133872459-50d2692c-72b8-40f3-82d8-13d3f80569b7.png)

Should just need to rebuild with the latest version of valheim's libraries to resolve

**Comment by projjm** [comment]
Thanks for the report, I'll aim to update this and my other mods for H&H by the end of this week.

**Comment by atticoos** [comment]
Hi @projjm, is there anything I can do to contribute in a compatibility release?

If I submit a PR that has any necessary changes, would you be able to assist with a Thunderstore release?

**Comment by projjm** [comment]
Hi Ajwhite, apologies for the delay, I've been stuggling to find free time recently as I am working on other projects. If you submit a PR, I would be happy to then assist with the Thunderstore/Nexus release.

**Comment by sbtoonz** [comment]
https://github.com/projjm/Valheim-Player-Trading/pull/2
